# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rango', '0002_auto_20190205_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=4684),
            preserve_default=False,
        ),
    ]
