# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Rango', '0004_auto_20190206_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='first_visit',
            field=models.DateField(default=datetime.datetime(2019, 2, 11, 16, 4, 3, 965006, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='page',
            name='last_visit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
